#!/usr/bin/env bash
# esercizio confronto due numeri

echo "inserisci due numeri"
read -pr "inserire il primo numero (x): " x
read -pr "inserire il secondo numero (y): " y

# da verificare se input è valorizzato

if [ "$x" -gt "$y" ]; then
  echo "\$x è maggiore di \$y"
elif [ "$x" -lt "$y" ]; then
  echo "\$x è minore di \$y"
elif [ "$x" = "$y" ]; then
  echo "\$x è uguale a \$y"
else
  echo "inserire due numeri"
  exit 1
fi
